apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: keycloak
  namespace: iam
spec:
  host: keycloak.example.com
  to:
    kind: Service
    name: keycloak
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
