apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: keycloak-operator
  namespace: openshift-operators
spec:
  channel: fast
  name: keycloak-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
