apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keycloak-metrics
  namespace: iam
spec:
  selector:
    matchLabels:
      app: keycloak
  endpoints:
    - port: mgmt
      path: /metrics
      interval: 30s
